language: c++
compiler: gcc
sudo: false
env:
  - PYTHON_VERSION="2.7"
before_install:
  # Move out of git directory to build root.
  - git fetch --unshallow --tags
  - git describe
  - cd ../..
  - pwd
install:
  # Download and configure conda.
  - wget http://repo.continuum.io/miniconda/Miniconda`echo ${PYTHON_VERSION:0:1} | grep 3`-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes
  - conda config --set show_channel_urls True
  - conda config --add channels conda-forge
  - source activate root
  - conda update --all
  # Fix root environment to have the correct Python version.
  - touch $HOME/miniconda/conda-meta/pinned
  - echo "python ${PYTHON_VERSION}.*" >> $HOME/miniconda/conda-meta/pinned
  - echo "conda-build 1.18.2" >> $HOME/miniconda/conda-meta/pinned
  - conda install python=$PYTHON_VERSION
  # Install basic conda dependencies.
  - touch $HOME/miniconda/conda-meta/pinned
  - conda install conda-build
  - conda install jinja2
  # Return to the git repo.
  - cd $TRAVIS_REPO_SLUG
  # Get the version.
  - VERSION=`python setup.py --version`
  - echo $VERSION
  # Create the test environment and install dependencies.
  - conda create --use-local -n testenv python=$PYTHON_VERSION
  - source activate testenv
  # Clean up downloads as there are quite a few and they waste space/memory.
  - conda clean -tipsy
  - rm -rfv $HOME/.cache/pip
script:
  # Building the recipe will run the tests too.
  - mv .git/shallow .git/shallow-not || true
  - conda build conda.recipe
  - mv .git/shallow-not .git/shallow || true
  # Run the benchmarks.
  - conda install --use-local -n testenv spams==$VERSION
